// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE0JVdMxk8q9DcZhBbC-94hPjZcvKjUmE',
    appId: '1:931536443452:web:358e4007a17f7c93c70b39',
    messagingSenderId: '931536443452',
    projectId: 'cleopatra-ff271',
    authDomain: 'cleopatra-ff271.firebaseapp.com',
    storageBucket: 'cleopatra-ff271.appspot.com',
    measurementId: 'G-E1182XJMLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcWsTKP-s-MO9sBNj8vxe5y6Z3rANcCNY',
    appId: '1:931536443452:android:80ca06388d2b376ac70b39',
    messagingSenderId: '931536443452',
    projectId: 'cleopatra-ff271',
    storageBucket: 'cleopatra-ff271.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUo9-XZrIFQGOCDcYU1GjOLaGTY4doZDM',
    appId: '1:931536443452:ios:80b4f96dba6acfabc70b39',
    messagingSenderId: '931536443452',
    projectId: 'cleopatra-ff271',
    storageBucket: 'cleopatra-ff271.appspot.com',
    iosClientId: '931536443452-68ujqohegiacfei6msuncskq9mq49usl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleopatra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUo9-XZrIFQGOCDcYU1GjOLaGTY4doZDM',
    appId: '1:931536443452:ios:80b4f96dba6acfabc70b39',
    messagingSenderId: '931536443452',
    projectId: 'cleopatra-ff271',
    storageBucket: 'cleopatra-ff271.appspot.com',
    iosClientId: '931536443452-68ujqohegiacfei6msuncskq9mq49usl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleopatra',
  );
}
